spring.application.name=QueueSense

#Port configuration
server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/queueSenseDb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api/v1

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-location=classpath:data.sql

#spring.security.user.name=deb
#spring.security.user.password=deb01

jwt.SecretKey=dwuftwffnjnchsbcy64adahcmjcixcubcscjn2g56dwkuqieoubcymiahtfxegaidko266iwkpmdiyq3g5fndjnyugc5w6wjot7f

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=debarshimandal01@gmail.com
spring.mail.password=xxxx xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
